on:
  push:
    branches:
      - debian-build

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: emrahayanoglu/build-dpkg-buster@debian-lib-build
        id: build
        with:
          args: --unsigned-source --unsigned-changes

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }}-${{ github.ref_name }}-armhf 
          path: /*.deb